name: Complete Build Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/complete-build-test.yml

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      registry:
        image: docker.io/registry:2
        ports:
          - 5000:5000
    strategy:
      matrix:
        arch: [amd64]

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          platforms: linux/${{ matrix.arch }}

      - name: Get latest versions
        run: python3 ./.github/scripts/get_latest_tags.py --repo erpnext --version develop

      - name: Set build args
        run: |
          echo "PYTHON_VERSION=3.11.6" >> "$GITHUB_ENV"
          echo "NODE_VERSION=20.19.2" >> "$GITHUB_ENV"

      - name: Build (test only)
        uses: docker/bake-action@v6.9.0
        with:
          source: .
          push: false
        env:
          REGISTRY_USER: localhost:5000/karlorz

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements-test.txt

      - name: Test
        run: venv/bin/pytest --color=yes