name: Simple Test

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - .github/workflows/simple-test.yml

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        
      - name: Echo test
        run: echo "Hello World"
        
      - name: Check Docker
        run: docker --version