name: Test GHCR Build (Fixed)

on:
  workflow_dispatch:
  push:
    branches:
      - dev
    paths:
      - images/production/**
      - docker-bake.hcl
      - .github/workflows/test-ghcr-fixed.yml

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v3
        with:
          image: tonistiigi/binfmt:latest
          platforms: all

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver-opts: network=host
          platforms: linux/amd64

      - name: Get latest versions
        run: python3 ./.github/scripts/get_latest_tags.py --repo erpnext --version develop

      - name: Set build args
        run: |
          echo "PYTHON_VERSION=3.11.6" >> "$GITHUB_ENV"
          echo "NODE_VERSION=20.19.2" >> "$GITHUB_ENV"

      - name: Test build (no push)
        uses: docker/bake-action@v6.9.0
        with:
          source: .
          push: false
          set: "*.platform=linux/amd64"
        env:
          REGISTRY_USER: test/karlorz

      - name: Login to GitHub Container Registry
        if: github.repository == 'karlorz/frappe_docker' && github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push to GHCR
        if: github.repository == 'karlorz/frappe_docker' && github.event_name != 'pull_request'
        uses: docker/bake-action@v6.9.0
        with:
          push: true
          set: "*.platform=linux/amd64"
        env:
          REGISTRY_USER: ghcr.io/karlorz